language: node_js
node_js:
  - "4.1"

install:
  - cd night-cyc-prototype
  - npm install

script:
  - gulp test

deploy:
  provider: heroku
  api_key:
    secure: fDeVPZ82KVKtxjltmBWbdNmnufPcExkeoGlbR9s1mED8zSx3FiZ3ttBENt5TiCWmm74fBtN9k56bxh5uRxqtuaUaL95ovu5ipmjzLiDJ2wGxUu0PtZ+94L/0DjelSut5qquqCwpyrc69T1LMqU8RF8YMTXZxsotGrZx1A6OEEMs2XkANiTWaedl1DrM3j5jyeTCp18/HEIdbb0+9v7naZKFBD4d0V1CUQIQHWMRR3e6XFgCGX1JwSQf9+JAsnPlSuXg2XqpMHX5KUa1Im1iEIYoK0JzlFINEIzaKNLuak0dNeFHijsC+C1JBPLnuvXBo4GElTeY/RVs17wietJObK0J7vVjUxaP69Z49e8C/YTHe/1Hx8GqqT5NRNosehAOtwUo5KIhGgGU5Qp2jfF2T8G0on7v/bqCAbbxAC5vFit2LxeiLGVvwC31eHG/sOf1SGuHFpoyHjITiK3puwUxuS+Cg2U6irnCR4uEhnUQEWvuA2UXIDtaYa8gh3OELHIgeW1IlDbOu/ivZysoydH73mmKXreWNO2JC7DQNanw9/yxhQrNBE1Fq9Y0PzIqvqMLXeF6GvyTDKEeVj8bdTlfLnOHfVnju0m1ISLQgnp2tNo+UrJ1h26J+IKRyHBxnkD2F4pgwHhNGC0P7DzHfZN2kTBrYk8+SqNjevSBfK8GYhkw=
